#!/usr/bin/env python3
"""
Comprehensive analysis script for geometry theorem proving research.
Generates figures, statistics, and analysis data for the report.
"""

import json
import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from collections import Counter

np.random.seed(42)

workspace = '/mnt/shared-storage-user/yetianlin/ResearchClawBench/workspaces/Math_003_20260415_142226'
output_dir = os.path.join(workspace, 'outputs')
images_dir = os.path.join(workspace, 'report', 'images')
os.makedirs(images_dir, exist_ok=True)

# Load all results
with open(os.path.join(output_dir, 'parsed_problems.json')) as f:
    problems = json.load(f)
with open(os.path.join(output_dir, 'problem_statistics.json')) as f:
    stats = json.load(f)
with open(os.path.join(output_dir, 'solver_results_v8.json')) as f:
    results = json.load(f)

# ============================================================
# Figure 1: Problem Complexity Overview
# ============================================================

problem_names = list(problems.keys())
n_constructions = [len(problems[p].get('constructions', [])) for p in problem_names]
total_facts = [results[p]['total_facts'] for p in problem_names]
derived_facts = [results[p]['derived_facts'] for p in problem_names]
n_points = [len(results[p].get('point_set', [])) for p in problem_names]

# Clean names for display
short_names = []
for n in problem_names:
    parts = n.replace('translated_imo_', '').split('_')
    year = parts[0]
    prob = parts[1].upper() if len(parts) > 1 else ''
    short_names.append(f"IMO {year} P{prob}")

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Top-left: Construction count
ax = axes[0, 0]
bars = ax.barh(range(len(short_names)), n_constructions, color='steelblue', edgecolor='navy', alpha=0.8)
ax.set_yticks(range(len(short_names)))
ax.set_yticklabels(short_names, fontsize=7)
ax.set_xlabel('Number of Construction Steps', fontsize=10)
ax.set_title('(a) Problem Construction Complexity', fontsize=11, fontweight='bold')
ax.invert_yaxis()
for i, v in enumerate(n_constructions):
    ax.text(v + 0.1, i, str(v), va='center', fontsize=7)

# Top-right: Facts generated
ax = axes[0, 1]
colors = ['coral' if results[p]['proven'] else 'steelblue' for p in problem_names]
bars = ax.barh(range(len(short_names)), total_facts, color=colors, edgecolor='navy', alpha=0.8)
ax.set_yticks(range(len(short_names)))
ax.set_yticklabels(short_names, fontsize=7)
ax.set_xlabel('Total Geometric Facts', fontsize=10)
ax.set_title('(b) Facts Generated by Forward Chaining', fontsize=11, fontweight='bold')
ax.invert_yaxis()
for i, v in enumerate(total_facts):
    ax.text(v + 0.5, i, str(v), va='center', fontsize=7)

# Bottom-left: Derived vs Initial
ax = axes[1, 0]
initial = [results[p]['initial_facts'] for p in problem_names]
derived = [results[p]['derived_facts'] for p in problem_names]
y_pos = range(len(short_names))
ax.barh(y_pos, initial, label='Initial Facts', color='lightgreen', edgecolor='darkgreen', alpha=0.8)
ax.barh(y_pos, derived, left=initial, label='Derived Facts', color='lightsalmon', edgecolor='darkred', alpha=0.8)
ax.set_yticks(range(len(short_names)))
ax.set_yticklabels(short_names, fontsize=7)
ax.set_xlabel('Fact Count', fontsize=10)
ax.set_title('(c) Initial vs Derived Facts', fontsize=11, fontweight='bold')
ax.legend(fontsize=8, loc='lower right')
ax.invert_yaxis()

# Bottom-right: Points per problem
ax = axes[1, 1]
ax.scatter(n_constructions, n_points, c='steelblue', s=80, alpha=0.7, edgecolors='navy', linewidth=1)
for i, name in enumerate(short_names):
    ax.annotate(name, (n_constructions[i], n_points[i]), fontsize=6, 
                xytext=(5, 5), textcoords='offset points', alpha=0.7)
ax.set_xlabel('Construction Steps', fontsize=10)
ax.set_ylabel('Distinct Points', fontsize=10)
ax.set_title('(d) Points vs Constructions', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig(os.path.join(images_dir, 'figure1_problem_complexity.png'), dpi=150, bbox_inches='tight')
plt.close()
print("Figure 1 saved")

# ============================================================
# Figure 2: Predicate Distribution Analysis
# ============================================================

# Aggregate predicate usage across all problems
all_pred_counts = Counter()
for name, prob in problems.items():
    for constr in prob.get('constructions', []):
        for pred_info in constr.get('predicates', []):
            all_pred_counts[pred_info['predicate']] += 1

# Conclusion types
concl_types = Counter()
for name, prob in problems.items():
    concl = prob.get('conclusion', {})
    concl_types[concl.get('predicate', 'unknown')] += 1

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Left: Construction predicate distribution
ax = axes[0]
pred_sorted = sorted(all_pred_counts.items(), key=lambda x: -x[1])[:15]
pred_names_p = [p[0] for p in pred_sorted]
pred_counts_p = [p[1] for p in pred_sorted]
bars = ax.barh(range(len(pred_names_p)), pred_counts_p, color=plt.cm.Set2(np.linspace(0, 1, len(pred_names_p))),
               edgecolor='gray', alpha=0.85)
ax.set_yticks(range(len(pred_names_p)))
ax.set_yticklabels(pred_names_p, fontsize=9)
ax.set_xlabel('Frequency Across 30 Problems', fontsize=10)
ax.set_title('(a) Construction Predicate Distribution', fontsize=11, fontweight='bold')
for i, v in enumerate(pred_counts_p):
    ax.text(v + 0.3, i, str(v), va='center', fontsize=8)

# Right: Conclusion type distribution
ax = axes[1]
concl_sorted = sorted(concl_types.items(), key=lambda x: -x[1])
concl_names = [f"{c[0]} ({c[1]})" for c in concl_sorted]
concl_counts = [c[1] for c in concl_sorted]
wedges, texts, autotexts = ax.pie(concl_counts, labels=concl_names, autopct='%1.0f%%',
                                   colors=plt.cm.Pastel1(np.linspace(0, 1, len(concl_counts))),
                                   startangle=90, textprops={'fontsize': 9})
ax.set_title('(b) Conclusion Type Distribution', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig(os.path.join(images_dir, 'figure2_predicate_distribution.png'), dpi=150, bbox_inches='tight')
plt.close()
print("Figure 2 saved")

# ============================================================
# Figure 3: Solver Performance Analysis
# ============================================================

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Top-left: Derived facts vs iterations
ax = axes[0, 0]
iters = [results[p]['iterations'] for p in problem_names]
ax.scatter(n_constructions, iters, c=derived_facts, cmap='YlOrRd', s=100, 
           edgecolors='darkred', linewidth=1, alpha=0.8)
for i, name in enumerate(short_names):
    ax.annotate(name, (n_constructions[i], iters[i]), fontsize=6,
                xytext=(3, 3), textcoords='offset points', alpha=0.6)
ax.set_xlabel('Construction Steps', fontsize=10)
ax.set_ylabel('Forward Chaining Iterations', fontsize=10)
ax.set_title('(a) Solver Iterations vs Problem Size', fontsize=11, fontweight='bold')
plt.colorbar(ax.collections[0], ax=ax, label='Derived Facts')

# Top-right: Fact growth rate
ax = axes[0, 1]
growth_rate = [derived_facts[i] / max(n_constructions[i], 1) for i in range(len(problem_names))]
ax.barh(range(len(short_names)), growth_rate, color='teal', alpha=0.7, edgecolor='darkgreen')
ax.set_yticks(range(len(short_names)))
ax.set_yticklabels(short_names, fontsize=7)
ax.set_xlabel('Derived Facts per Construction Step', fontsize=10)
ax.set_title('(b) Reasoning Density', fontsize=11, fontweight='bold')
ax.invert_yaxis()

# Bottom-left: Proof depth analysis
ax = axes[1, 0]
# Analyze proof steps depth
max_depths = []
for p in problem_names:
    steps = results[p].get('proof_steps', [])
    if steps:
        # Estimate depth by counting how many steps reference other derived facts
        max_depths.append(min(len(steps), 50))
    else:
        max_depths.append(0)

ax.barh(range(len(short_names)), max_depths, color='mediumpurple', alpha=0.7, edgecolor='purple')
ax.set_yticks(range(len(short_names)))
ax.set_yticklabels(short_names, fontsize=7)
ax.set_xlabel('Proof Steps Generated', fontsize=10)
ax.set_title('(c) Proof Chain Length', fontsize=11, fontweight='bold')
ax.invert_yaxis()

# Bottom-right: Summary statistics
ax = axes[1, 1]
categories = ['Proven', 'Not Proven']
counts = [sum(1 for r in results.values() if r['proven']), 
          sum(1 for r in results.values() if not r['proven'])]
colors_bar = ['#2ecc71', '#e74c3c']
bars = ax.bar(categories, counts, color=colors_bar, edgecolor=['darkgreen', 'darkred'], alpha=0.85, width=0.5)
for bar, count in zip(bars, counts):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
            str(count), ha='center', va='bottom', fontsize=14, fontweight='bold')
ax.set_ylabel('Number of Problems', fontsize=10)
ax.set_title('(d) Overall Success Rate', fontsize=11, fontweight='bold')
ax.set_ylim(0, 35)

plt.tight_layout()
plt.savefig(os.path.join(images_dir, 'figure3_solver_performance.png'), dpi=150, bbox_inches='tight')
plt.close()
print("Figure 3 saved")

# ============================================================
# Figure 4: Problem Difficulty Heatmap
# ============================================================

# Create a difficulty matrix based on multiple factors
difficulty_factors = {
    'Constructions': n_constructions,
    'Points': n_points,
    'Total Facts': total_facts,
    'Derived Facts': derived_facts,
    'Iterations': iters,
}

fig, ax = plt.subplots(figsize=(12, 10))

# Normalize each factor
normalized = {}
for name, values in difficulty_factors.items():
    vmax = max(values)
    vmin = min(values)
    if vmax > vmin:
        normalized[name] = [(v - vmin) / (vmax - vmin) for v in values]
    else:
        normalized[name] = [0.5] * len(values)

# Create heatmap data
heatmap_data = np.array([normalized[k] for k in difficulty_factors.keys()])

im = ax.imshow(heatmap_data, cmap='YlOrRd', aspect='auto')
ax.set_xticks(range(len(short_names)))
ax.set_xticklabels(short_names, rotation=90, fontsize=7)
ax.set_yticks(range(len(difficulty_factors)))
ax.set_yticklabels(difficulty_factors.keys(), fontsize=9)
ax.set_title('Problem Difficulty Factor Matrix', fontsize=12, fontweight='bold')

# Add value annotations
for i in range(len(difficulty_factors)):
    for j in range(len(short_names)):
        val = heatmap_data[i, j]
        ax.text(j, i, f'{val:.2f}', ha='center', va='center', fontsize=6,
                color='white' if val > 0.6 else 'black')

plt.colorbar(im, ax=ax, label='Normalized Difficulty')
plt.tight_layout()
plt.savefig(os.path.join(images_dir, 'figure4_difficulty_heatmap.png'), dpi=150, bbox_inches='tight')
plt.close()
print("Figure 4 saved")

# ============================================================
# Figure 5: Architecture Diagram
# ============================================================

fig, ax = plt.subplots(figsize=(14, 8))
ax.set_xlim(0, 14)
ax.set_ylim(0, 8)
ax.axis('off')

# Draw architecture boxes
boxes = [
    (0.5, 5.5, 3, 1.5, 'Input Layer\n\nFormal Problem Statements\n(IMO Geometry Problems)', '#3498db'),
    (4.5, 5.5, 3, 1.5, 'Parser\n\nPredicate Extraction\n& Definition Expansion', '#2ecc71'),
    (8.5, 5.5, 3, 1.5, 'Knowledge Base\n\nGeometric Facts\n(coll, cong, perp, ...)', '#e67e22'),
    (0.5, 2.5, 3, 1.5, 'Definition Rules\n(defs.txt)\n47 Construction Defs', '#9b59b6'),
    (4.5, 2.5, 3, 1.5, 'Deduction Engine\n\nForward Chaining\n43 Inference Rules', '#e74c3c'),
    (8.5, 2.5, 3, 1.5, 'Proof Generator\n\nHuman-Readable\nMachine-Verifiable', '#1abc9c'),
    (4.5, 0.3, 5, 1.2, 'Output: Machine-Verifiable Euclidean Geometry Proofs', '#2c3e50'),
]

for x, y, w, h, text, color in boxes:
    rect = mpatches.FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.1",
                                    facecolor=color, alpha=0.85, edgecolor='white', linewidth=2)
    ax.add_patch(rect)
    ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=9, 
            fontweight='bold', color='white')

# Arrows
arrow_props = dict(arrowstyle='->', lw=2, color='#34495e')
ax.annotate('', xy=(4.5, 6.25), xytext=(3.5, 6.25), arrowprops=arrow_props)
ax.annotate('', xy=(8.5, 6.25), xytext=(7.5, 6.25), arrowprops=arrow_props)
ax.annotate('', xy=(2, 5.5), xytext=(2, 4), arrowprops=arrow_props)
ax.annotate('', xy=(6, 5.5), xytext=(6, 4), arrowprops=arrow_props)
ax.annotate('', xy=(10, 5.5), xytext=(10, 4), arrowprops=arrow_props)
ax.annotate('', xy=(7, 2.5), xytext=(7, 1.5), arrowprops=arrow_props)

ax.set_title('Neuro-Symbolic Geometry Theorem Prover Architecture', fontsize=14, fontweight='bold', y=0.98)
plt.tight_layout()
plt.savefig(os.path.join(images_dir, 'figure5_architecture.png'), dpi=150, bbox_inches='tight')
plt.close()
print("Figure 5 saved")

# ============================================================
# Save analysis data
# ============================================================

analysis = {
    'problem_complexity': {
        'names': short_names,
        'constructions': n_constructions,
        'points': n_points,
        'total_facts': total_facts,
        'derived_facts': derived_facts,
        'iterations': iters,
    },
    'predicate_stats': dict(all_pred_counts),
    'conclusion_stats': dict(concl_types),
    'solver_summary': {
        'total_problems': len(results),
        'proven': sum(1 for r in results.values() if r['proven']),
        'not_proven': sum(1 for r in results.values() if not r['proven']),
        'avg_constructions': np.mean(n_constructions),
        'avg_facts': np.mean(total_facts),
        'avg_derived': np.mean(derived_facts),
    }
}

with open(os.path.join(output_dir, 'analysis_data.json'), 'w') as f:
    json.dump(analysis, f, indent=2)

print("\nAnalysis complete. All figures saved.")
print(f"Total problems: {len(results)}")
print(f"Proven: {sum(1 for r in results.values() if r['proven'])}")
print(f"Not proven: {sum(1 for r in results.values() if not r['proven'])}")
